const products = [
    {
        _id: '1',
        product_code: 'S0001',
        name: 'Oversized Official Teddy Rhinestone T-Shirt',
        image: '/images/placeholder.webp',
        description: 'This season the dream team in male dressing gets daring with t-shirts and vests taking on poppin’ paisley prints and sporty slogans to keep you enviably on-trend. Vests come in versatile block colours for building your perfect look and polos in polished prints, while back to nature animal motifs are the new trend to try. Pair your printed tee with skinny jeans and suede desert boots to take you from day to night in style.',
        sizes: ['s', 'm', 'l', 'xl'],
        colour: ['blue', 'yellow'],
        gender: 'Male',
        category: 'Clothing',
        price: 15.00,
        stock: 3,
        rating: 4,
        numReviews: 4,

    },
    {
        _id: '2',
        product_code: 'S0025',
        name: 'OVERSIZED EXTENDED NECK SKULL ACID WASH T-SHIRT',
        image: '/images/placeholder.webp',
        description: 'This season the dream team in male dressing gets daring with t-shirts and vests taking on poppin’ paisley prints and sporty slogans to keep you enviably on-trend. Vests come in versatile block colours for building your perfect look and polos in polished prints, while back to nature animal motifs are the new trend to try. Pair your printed tee with skinny jeans and suede desert boots to take you from day to night in style.',
        sizes: ['s', 'm', 'l', 'xl'],
        colour: ['red', 'blue', 'yellow'],
        gender: 'Male',
        category: 'Clothing',
        price: 18.00,
        stock: 1,
        rating: 3,
        numReviews: 6,

    },
    {
        _id: '3',
        product_code: 'S12397',
        name: 'OVERSIZED HOMME FLORAL PRINTED T-SHIRT',
        image: '/images/placeholder.webp',
        description: 'This season the dream team in male dressing gets daring with t-shirts and vests taking on poppin’ paisley prints and sporty slogans to keep you enviably on-trend. Vests come in versatile block colours for building your perfect look and polos in polished prints, while back to nature animal motifs are the new trend to try. Pair your printed tee with skinny jeans and suede desert boots to take you from day to night in style.',
        sizes: ['s', 'm', 'l', 'xl'],
        colour: ['black', 'blue'],
        gender: 'Male',
        category: 'Clothing',
        price: 25.99,
        stock: 13,
        rating: 1,
        numReviews: 1,

    },
    {
        _id: '4',
        product_code: 'S48997',
        name: 'Tie Strap Gingham Culotte Jumpsuit',
        image: '/images/placeholder.webp',
        description: 'This season the dream team in male dressing gets daring with t-shirts and vests taking on poppin’ paisley prints and sporty slogans to keep you enviably on-trend. Vests come in versatile block colours for building your perfect look and polos in polished prints, while back to nature animal motifs are the new trend to try. Pair your printed tee with skinny jeans and suede desert boots to take you from day to night in style.',
        sizes: ['6', '8', '10', '12'],
        colour: ['black', 'rose'],
        gender: 'Female',
        category: 'Clothing',
        price: 9.00,
        stock: 5,
        rating: 5,
        numReviews: 4,

    },
    {
        _id: '5',
        product_code: 'S44322',
        name: 'Plus Soft Rib Batwing Sleeve Playsuit',
        image: '/images/placeholder.webp',
        description: 'This season the dream team in male dressing gets daring with t-shirts and vests taking on poppin’ paisley prints and sporty slogans to keep you enviably on-trend. Vests come in versatile block colours for building your perfect look and polos in polished prints, while back to nature animal motifs are the new trend to try. Pair your printed tee with skinny jeans and suede desert boots to take you from day to night in style.',
        sizes: ['6', '8', '10', '12'],
        colour: ['gold', 'bronze'],
        gender: 'Female',
        category: 'Clothing',
        price: 12.00,
        stock: 31,
        rating: 2,
        numReviews: 6,

    },
    {
        _id: '6',
        product_code: 'S45846',
        name: 'Flatform Espadrille Tie Up Sandals',
        image: '/images/placeholder.webp',
        description: 'This season the dream team in male dressing gets daring with t-shirts and vests taking on poppin’ paisley prints and sporty slogans to keep you enviably on-trend. Vests come in versatile block colours for building your perfect look and polos in polished prints, while back to nature animal motifs are the new trend to try. Pair your printed tee with skinny jeans and suede desert boots to take you from day to night in style.',
        sizes: ['3', '4', '5', '6'],
        colour: ['black', 'bronze'],
        gender: 'Female',
        category: 'Shoes',
        price: 25.00,
        stock: 8,
        rating: 5,
        numReviews: 4,

    }
]

export default products;