version: "3"
services: 
    ecommerce:
        container_name: docker-ecommerce-website
        restart: always
        build: .
        ports: 
            - 5000:5000
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - '27018:27017'